url: https://tnoller.github.io
baseurl: /uvsg/

# Site settings
title: United Veterans Service Group
email: # your-email@domain.com
description: "Providing Solutions for Government Contracting. A Service-Disabled Veteran-Owned Small Business."


# Team names, titles and social links
people:
- name: Jeff Boers
  pic: jb
  position: President
  social:
    # - title: # twitter
    #   url: #
  bio: "Jeff Boers, President of United Veterans Service Group, is a widely accomplished, well-credentialed, and self-directed Executive Leader and Special Operations veteran with over 30 years leading complex organizations and programs on a global stage."
- name: Paul
  pic: p
  position: 
  social:
    # - title: # twitter
    #   url: #
  bio: "Paul..."  
- name: Chris Owen
  pic: co
  position: 
  social:
    # - title: # twitter
    #   url: #
  bio: "Chris..."  
- name: Tom Whitehead
  pic: tw
  position: 
  social:
    # - title: # twitter
    #   url: #
  bio: "Tom..."   

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: linkedin
  #   url: # http://twitter.com/jekyllrb
 
# Postal address (add as many lines as necessary)
address:
  - line: # 3481 Melrose Place
  - line: # Beverly Hills, CA 90210

# Web analytics settings
analytics:
  google: #Google Analytics tracking code here

# Build settings
markdown: kramdown
permalink: pretty
